[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile.production"

[deploy]
healthcheckPath = "/api/system/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[[services]]
name = "persian-legal-ai-backend"

[services.variables]
PORT = "8000"
ENVIRONMENT = "production"
DATABASE_URL = "sqlite:///persian_legal_ai.db"
PERSIAN_BERT_MODEL = "HooshvareLab/bert-fa-base-uncased"
LOG_LEVEL = "INFO"