#!/bin/bash
# Undo script for Persian Legal AI Project Organization
# Generated automatically - DO NOT EDIT MANUALLY

echo "🔄 Reversing project organization..."

mv "/workspace/docs/reports/BOLT_INTEGRATION_COMPLETE.md" "/workspace/BOLT_INTEGRATION_COMPLETE.md"
mv "/workspace/docs/reports/CLEANUP_SUMMARY.md" "/workspace/CLEANUP_SUMMARY.md"
mv "/workspace/docs/reports/MERGE_COMPLETION_REPORT.md" "/workspace/MERGE_COMPLETION_REPORT.md"
mv "/workspace/docs/reports/PERSIAN_AI_ENHANCEMENT_COMPLETION_REPORT.md" "/workspace/PERSIAN_AI_ENHANCEMENT_COMPLETION_REPORT.md"
mv "/workspace/docs/reports/PERSIAN_LEGAL_AI_AUDIT_COMPLETION_REPORT.md" "/workspace/PERSIAN_LEGAL_AI_AUDIT_COMPLETION_REPORT.md"
mv "/workspace/docs/reports/PHASE_3_COMPLETION_SUMMARY.md" "/workspace/PHASE_3_COMPLETION_SUMMARY.md"
mv "/workspace/docs/reports/PHASE_CRITICAL_PRODUCTION_ISSUES_RESOLVED.md" "/workspace/PHASE_CRITICAL_PRODUCTION_ISSUES_RESOLVED.md"
mv "/workspace/docs/reports/RECOVERY_REPORT.md" "/workspace/RECOVERY_REPORT.md"
mv "/workspace/docs/reports/SAFE_MERGE_COMPLETION_REPORT.md" "/workspace/SAFE_MERGE_COMPLETION_REPORT.md"
mv "/workspace/docs/reports/VISUAL_UI_TEST_REPORT.md" "/workspace/VISUAL_UI_TEST_REPORT.md"
mv "/workspace/docs/reports/integration-report.md" "/workspace/integration-report.md"
mv "/workspace/docs/guides/DEPLOYMENT_GUIDE.md" "/workspace/DEPLOYMENT_GUIDE.md"
mv "/workspace/docs/guides/START_SYSTEM.md" "/workspace/START_SYSTEM.md"
mv "/workspace/docs/guides/backend-implementation-guide.md" "/workspace/backend-implementation-guide.md"
mv "/workspace/docs/analysis/BACKEND_MAIN_FILES_ANALYSIS.md" "/workspace/BACKEND_MAIN_FILES_ANALYSIS.md"
mv "/workspace/docs/analysis/analysis_report.txt" "/workspace/analysis_report.txt"
mv "/workspace/tests/e2e/test_frontend.html" "/workspace/test_frontend.html"
mv "/workspace/tests/integration/test_integration.py" "/workspace/test_integration.py"
mv "/workspace/tests/integration/test_production_system.py" "/workspace/test_production_system.py"
mv "/workspace/scripts/utils/check-bolt-endpoints.sh" "/workspace/check-bolt-endpoints.sh"
mv "/workspace/scripts/utils/comprehensive-test.sh" "/workspace/comprehensive-test.sh"
mv "/workspace/scripts/utils/fix-imports.sh" "/workspace/fix-imports.sh"
mv "/workspace/scripts/utils/fix-quotes.sh" "/workspace/fix-quotes.sh"
mv "/workspace/scripts/maintenance/persian_legal_ai_recovery.sh" "/workspace/persian_legal_ai_recovery.sh"
mv "/workspace/scripts/deployment/safe-merge-to-main.sh" "/workspace/safe-merge-to-main.sh"
mv "/workspace/scripts/deployment/safe-merge.sh" "/workspace/safe-merge.sh"
mv "/workspace/scripts/utils/smart-analysis.sh" "/workspace/smart-analysis.sh"
mv "/workspace/scripts/utils/smart-migration.sh" "/workspace/smart-migration.sh"
mv "/workspace/scripts/maintenance/system_health_check.py" "/workspace/system_health_check.py"
mv "/workspace/scripts/start_system.py" "/workspace/start_system.py"
mv "/workspace/scripts/utils/backend-validator-simple.js" "/workspace/backend-validator-simple.js"
mv "/workspace/scripts/utils/backend-validator.js" "/workspace/backend-validator.js"
mv "/workspace/scripts/utils/dependency-analyzer.js" "/workspace/dependency-analyzer.js"
mv "/workspace/scripts/utils/dependency-analyzer.ts" "/workspace/dependency-analyzer.ts"
mv "/workspace/scripts/utils/route-updater.js" "/workspace/route-updater.js"
mv "/workspace/scripts/utils/route-updater.ts" "/workspace/route-updater.ts"
mv "/workspace/configs/production/docker-compose.production.yml" "/workspace/docker-compose.production.yml"
mv "/workspace/configs/development/docker-compose.yml" "/workspace/docker-compose.yml"
mv "/workspace/backup/databases/persian_legal_ai.db" "/workspace/persian_legal_ai.db"

echo "✅ Organization reversal completed!"
echo "📁 You may need to manually remove empty directories if desired."
